// ==========================================
// 复利提醒模板 + 场景模板
// ==========================================

import { CompoundCategory, Reminder, SceneTemplateData } from '@/types/reminder';

type ReminderTemplate = Omit<Reminder, 'id' | 'createdAt' | 'sortOrder'>;

/** 复利提醒预设模板 */
export const compoundTemplates: Record<CompoundCategory, ReminderTemplate[]> = {
  health: [
    {
      title: '晨起一杯温水',
      time: '07:00',
      repeat: 'daily',
      category: 'health',
      urgency: 'gentle',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '早安 ☀️ 新的一天开始了。你值得被好好对待，从一杯温水开始。',
    },
    {
      title: '上午站立活动',
      time: '10:30',
      repeat: 'weekdays',
      category: 'health',
      urgency: 'gentle',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: false,
    },
    {
      title: '午后散步',
      time: '13:30',
      repeat: 'weekdays',
      category: 'health',
      urgency: 'gentle',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: false,
      customMessage: '吃完午饭了吧？出去走走，阳光和新鲜空气是最好的下午茶。',
    },
    {
      title: '下午喝水提醒',
      time: '15:30',
      repeat: 'daily',
      category: 'health',
      urgency: 'gentle',
      enabled: true,
      soundEnabled: false,
      webhookEnabled: false,
    },
    {
      title: '运动时间',
      time: '18:30',
      repeat: 'weekdays',
      category: 'health',
      urgency: 'firm',
      enabled: false,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '动起来吧！30分钟后的你会感谢现在的决定。',
    },
    {
      title: '准备入睡',
      time: '22:30',
      repeat: 'daily',
      category: 'health',
      urgency: 'gentle',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '今天辛苦了 🌙 放下手机，让身体好好休息。明天的你会感谢现在的决定。',
    },
  ],
  finance: [
    {
      title: '每日记账',
      time: '21:30',
      repeat: 'daily',
      category: 'finance',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: false,
      webhookEnabled: false,
      customMessage: '花两分钟记录今天的支出，清晰的财务就是清晰的人生。',
    },
    {
      title: '投资/理财检查',
      time: '10:00',
      repeat: 'weekly',
      weekDays: [1],
      category: 'finance',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: true,
      webhookEnabled: false,
    },
  ],
  relation: [
    {
      title: '联系一个重要的人',
      time: '12:00',
      repeat: 'weekly',
      weekDays: [3],
      category: 'relation',
      urgency: 'gentle',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '想想谁最近让你想起了温暖？发条消息给 ta 吧。',
    },
    {
      title: '表达感谢',
      time: '17:00',
      repeat: 'weekly',
      weekDays: [5],
      category: 'relation',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: false,
      webhookEnabled: false,
      customMessage: '这周谁帮助了你？真诚地说一声谢谢。',
    },
  ],
  creation: [
    {
      title: '创作时间',
      time: '09:00',
      endTime: '11:00',
      repeat: 'weekdays',
      category: 'creation',
      urgency: 'firm',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '最重要的事，用最好的状态去做。开始你的创作。',
    },
    {
      title: '阅读/输入时间',
      time: '21:00',
      repeat: 'daily',
      category: 'creation',
      urgency: 'firm',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '每天30分钟阅读，一年就是182小时。打开那本书吧。',
    },
    {
      title: '灵感记录',
      time: '22:00',
      repeat: 'daily',
      category: 'creation',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: true,
      webhookEnabled: false,
      customMessage: '记录今天的灵感和想法，未来的你会感谢现在的记录。',
    },
  ],
  joy: [
    {
      title: '做点喜欢的事',
      time: '10:00',
      repeat: 'daily',
      category: 'joy',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: false,
      webhookEnabled: false,
      customMessage: '今天是属于你的。做点让自己开心的事，不需要理由。',
    },
    {
      title: '冥想/放空',
      time: '07:30',
      repeat: 'daily',
      category: 'joy',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: true,
      webhookEnabled: false,
      customMessage: '给自己5分钟安静的时间，从平静开始新的一天。',
    },
    {
      title: '感恩记录',
      time: '22:00',
      repeat: 'daily',
      category: 'joy',
      urgency: 'firm',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '今天做了什么？学到了什么？明天想做什么？三个问题，三分钟。',
    },
  ],
  skill: [
    {
      title: '深度工作时间',
      time: '09:00',
      endTime: '11:00',
      repeat: 'weekdays',
      category: 'skill',
      urgency: 'firm',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: true,
      customMessage: '最重要的事，用最好的状态去做。开始你的深度工作。',
    },
    {
      title: '下午专注时段',
      time: '14:00',
      endTime: '16:00',
      repeat: 'weekdays',
      category: 'skill',
      urgency: 'firm',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: false,
    },
    {
      title: '学习新技能',
      time: '20:00',
      repeat: 'daily',
      category: 'skill',
      urgency: 'firm',
      enabled: false,
      soundEnabled: true,
      webhookEnabled: false,
      customMessage: '你说过想成为更好的自己，现在就是那个时刻。',
    },
  ],
  cognition: [
    {
      title: '深度阅读',
      time: '08:00',
      repeat: 'daily',
      category: 'cognition',
      urgency: 'firm',
      enabled: true,
      soundEnabled: true,
      webhookEnabled: false,
      customMessage: '每天30分钟深度阅读，积累认知复利。',
    },
    {
      title: '反思与记录',
      time: '21:30',
      repeat: 'daily',
      category: 'cognition',
      urgency: 'gentle',
      enabled: false,
      soundEnabled: true,
      webhookEnabled: false,
      customMessage: '今天学到了什么新东西？花5分钟写下来。',
    },
  ],
  custom: [],
};

/** 场景模板 */
export const sceneTemplates: SceneTemplateData[] = [
  {
    id: 'workday',
    name: '工作日',
    icon: '💼',
    description: '高效工作 + 身体关爱',
    type: 'workday',
    reminders: [
      { title: '晨起一杯温水', time: '07:00', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '深度工作', time: '09:00', endTime: '11:00', repeat: 'weekdays', category: 'skill', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '站立活动', time: '10:30', repeat: 'weekdays', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: false },
      { title: '午休散步', time: '13:00', repeat: 'weekdays', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: false, webhookEnabled: false },
      { title: '下午专注', time: '14:00', endTime: '16:00', repeat: 'weekdays', category: 'skill', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: false },
      { title: '喝水', time: '15:30', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: false, webhookEnabled: false },
      { title: '阅读', time: '21:00', repeat: 'daily', category: 'creation', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '感恩记录', time: '22:00', repeat: 'daily', category: 'joy', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '准备入睡', time: '22:30', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: true },
    ],
  },
  {
    id: 'study',
    name: '学习日',
    icon: '📚',
    description: '沉浸学习 + 心智滋养',
    type: 'study',
    reminders: [
      { title: '晨起准备', time: '07:00', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '晨间冥想', time: '07:30', repeat: 'daily', category: 'joy', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: false },
      { title: '专注学习 · 上午', time: '08:30', endTime: '11:30', repeat: 'daily', category: 'skill', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '休息放松', time: '12:00', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: false, webhookEnabled: false },
      { title: '专注学习 · 下午', time: '14:00', endTime: '17:00', repeat: 'daily', category: 'skill', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '散步思考', time: '17:30', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: false },
      { title: '复习整理', time: '20:00', repeat: 'daily', category: 'creation', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: false },
      { title: '感恩记录', time: '22:00', repeat: 'daily', category: 'joy', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
    ],
  },
  {
    id: 'rest',
    name: '休息日',
    icon: '🌿',
    description: '放松恢复 + 关系滋养',
    type: 'rest',
    reminders: [
      { title: '自然醒 · 温水', time: '08:30', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: false },
      { title: '做点喜欢的事', time: '10:00', repeat: 'daily', category: 'joy', urgency: 'gentle', enabled: true, soundEnabled: false, webhookEnabled: false, customMessage: '今天是休息日。做点让自己开心的事，不需要理由。' },
      { title: '联系朋友/家人', time: '11:00', repeat: 'daily', category: 'relation', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '户外活动', time: '15:00', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: false, customMessage: '出去走走，让身体感受自然。' },
      { title: '轻松阅读', time: '20:00', repeat: 'daily', category: 'creation', urgency: 'gentle', enabled: true, soundEnabled: false, webhookEnabled: false },
      { title: '周复盘', time: '21:00', repeat: 'weekly', weekDays: [0], category: 'joy', urgency: 'firm', enabled: true, soundEnabled: true, webhookEnabled: true },
      { title: '早点休息', time: '22:00', repeat: 'daily', category: 'health', urgency: 'gentle', enabled: true, soundEnabled: true, webhookEnabled: true, customMessage: '休息日也要早睡。储备能量，迎接新的一周。' },
    ],
  },
];
